-- Seed for stock_symbol_profiles (US)
-- Run after SUPABASE_SETUP_STOCK_SYMBOL_PROFILES.sql
insert into public.stock_symbol_profiles(symbol, region, sector, industry, priority)
values
  ('AAPL', 'US', 'テクノロジー', 'Consumer Electronics', 10),
  ('ACWI', 'US', 'グローバル株式ETF', 'All Country World Index ETF', 20),
  ('AGG', 'US', '債券ETF', 'US Aggregate Bond ETF', 30),
  ('AMD', 'US', 'テクノロジー', 'Semiconductors', 40),
  ('AMZN', 'US', '一般消費財', 'E-Commerce', 50),
  ('ARKF', 'US', 'テーマETF', 'Fintech Innovation ETF', 60),
  ('ARKG', 'US', 'テーマETF', 'Genomics Innovation ETF', 70),
  ('ARKK', 'US', 'テーマETF', 'Innovation ETF', 80),
  ('ASML', 'US', 'テクノロジー', 'Semiconductor Equipment', 90),
  ('AVGO', 'US', 'テクノロジー', 'Semiconductors', 100),
  ('AZN', 'US', 'ヘルスケア', 'Pharmaceuticals', 110),
  ('BND', 'US', '債券ETF', 'US Total Bond Market ETF', 120),
  ('BP', 'US', 'エネルギー', 'Integrated Oil & Gas', 130),
  ('DGRO', 'US', '高配当ETF', 'US Dividend Growth ETF', 140),
  ('DIA', 'US', '指数ETF', 'Dow Jones Industrial Average ETF', 150),
  ('EEM', 'US', '海外株式ETF', 'Emerging Markets ETF', 160),
  ('EFA', 'US', '海外株式ETF', 'Developed Markets ex-US ETF', 170),
  ('EMB', 'US', '債券ETF', 'Emerging Market Bond ETF', 180),
  ('EWJ', 'US', '海外株式ETF', 'Japan Equity ETF', 190),
  ('GDX', 'US', 'コモディティ関連株ETF', 'Gold Miners ETF', 200),
  ('GLD', 'US', 'コモディティETF', 'Gold ETF', 210),
  ('GOOGL', 'US', 'コミュニケーション', 'Internet Services', 220),
  ('HSBC', 'US', '金融', 'Banks', 230),
  ('HYG', 'US', '債券ETF', 'High Yield Bond ETF', 240),
  ('IEF', 'US', '債券ETF', '7-10Y Treasury ETF', 250),
  ('IVV', 'US', '指数ETF', 'S&P 500 ETF', 260),
  ('IWM', 'US', '指数ETF', 'Russell 2000 ETF', 270),
  ('LQD', 'US', '債券ETF', 'Investment Grade Corporate Bond ETF', 280),
  ('MCHI', 'US', '海外株式ETF', 'China Equity ETF', 290),
  ('META', 'US', 'コミュニケーション', 'Internet Platforms', 300),
  ('MSFT', 'US', 'テクノロジー', 'Software', 310),
  ('NVDA', 'US', 'テクノロジー', 'Semiconductors', 320),
  ('NVO', 'US', 'ヘルスケア', 'Pharmaceuticals', 330),
  ('ORCL', 'US', 'テクノロジー', 'Enterprise Software', 340),
  ('QQQ', 'US', '指数ETF', 'NASDAQ-100 ETF', 350),
  ('RIO', 'US', '素材', 'Metals & Mining', 360),
  ('RSP', 'US', '指数ETF', 'S&P 500 Equal Weight ETF', 370),
  ('SAP', 'US', 'テクノロジー', 'Application Software', 380),
  ('SCHD', 'US', '高配当ETF', 'US Dividend Equity ETF', 390),
  ('SHEL', 'US', 'エネルギー', 'Integrated Oil & Gas', 400),
  ('SHOP', 'US', 'テクノロジー', 'E-Commerce Platforms', 410),
  ('SHY', 'US', '債券ETF', '1-3Y Treasury ETF', 420),
  ('SLV', 'US', 'コモディティETF', 'Silver ETF', 430),
  ('SMH', 'US', 'セクターETF', 'Semiconductor ETF', 440),
  ('SOXX', 'US', 'セクターETF', 'Semiconductor ETF', 450),
  ('SPY', 'US', '指数ETF', 'S&P 500 ETF', 460),
  ('TIP', 'US', '債券ETF', 'TIPS ETF', 470),
  ('TLT', 'US', '債券ETF', '20Y+ Treasury ETF', 480),
  ('TSLA', 'US', '一般消費財', 'Automobiles', 490),
  ('UBER', 'US', 'テクノロジー', 'Ride Sharing', 500),
  ('USO', 'US', 'コモディティETF', 'Oil ETF', 510),
  ('VNQ', 'US', '不動産ETF', 'US REIT ETF', 520),
  ('VNQI', 'US', '不動産ETF', 'Global ex-US REIT ETF', 530),
  ('VOO', 'US', '指数ETF', 'S&P 500 ETF', 540),
  ('VT', 'US', 'グローバル株式ETF', 'Total World Stock ETF', 550),
  ('VTI', 'US', '指数ETF', 'US Total Market ETF', 560),
  ('VXUS', 'US', '海外株式ETF', 'Total International Stock ETF', 570),
  ('XBI', 'US', 'セクターETF', 'Biotech ETF', 580),
  ('XLB', 'US', 'セクターETF', 'Materials Select Sector ETF', 590),
  ('XLC', 'US', 'セクターETF', 'Communication Services Select Sector ETF', 600),
  ('XLE', 'US', 'セクターETF', 'Energy Select Sector ETF', 610),
  ('XLF', 'US', 'セクターETF', 'Financial Select Sector ETF', 620),
  ('XLI', 'US', 'セクターETF', 'Industrial Select Sector ETF', 630),
  ('XLK', 'US', 'セクターETF', 'Technology Select Sector ETF', 640),
  ('XLP', 'US', 'セクターETF', 'Consumer Staples Select Sector ETF', 650),
  ('XLU', 'US', 'セクターETF', 'Utilities Select Sector ETF', 660),
  ('XLV', 'US', 'セクターETF', 'Health Care Select Sector ETF', 670),
  ('XLY', 'US', 'セクターETF', 'Consumer Discretionary Select Sector ETF', 680),
  ('XOP', 'US', 'セクターETF', 'Oil & Gas Exploration ETF', 690),
  ('VRT', 'US', '資本財・産業', 'Electrical Components & Equipment', 700)
on conflict (symbol) do update
set region = excluded.region,
    sector = excluded.sector,
    industry = excluded.industry,
    priority = excluded.priority,
    updated_at = now();
