-- Seed for stock_symbol_profiles (JP/UK/EU)
-- Run after SUPABASE_SETUP_STOCK_SYMBOL_PROFILES.sql
insert into public.stock_symbol_profiles(symbol, region, sector, industry, priority)
values
  ('1475.T', 'JP', '日本総合', 'Japan Broad Market', 10),
  ('6758.T', 'JP', 'テクノロジー', 'Consumer Electronics', 20),
  ('6861.T', 'JP', 'テクノロジー', 'Electronic Components', 30),
  ('7203.T', 'JP', '資本財・産業', 'Auto Manufacturers', 40),
  ('8035.T', 'JP', 'テクノロジー', 'Semiconductor Equipment', 50),
  ('8058.T', 'JP', '資本財・産業', 'Diversified Trading', 60),
  ('8306.T', 'JP', '金融', 'Banks', 70),
  ('8411.T', 'JP', '金融', 'Banks', 80),
  ('9432.T', 'JP', 'コミュニケーション', 'Telecom Services', 90),
  ('9433.T', 'JP', 'コミュニケーション', 'Telecom Services', 100),
  ('9984.T', 'JP', '一般消費財', 'Holding Companies', 110),
  ('AZN.L', 'UK', 'ヘルスケア', 'Pharmaceuticals', 120),
  ('BARC.L', 'UK', '金融', 'Banks', 130),
  ('BATS.L', 'UK', '生活必需品', 'Tobacco', 140),
  ('BP.L', 'UK', 'エネルギー', 'Integrated Oil & Gas', 150),
  ('GSK.L', 'UK', 'ヘルスケア', 'Pharmaceuticals', 160),
  ('HSBA.L', 'UK', '金融', 'Banks', 170),
  ('LLOY.L', 'UK', '金融', 'Banks', 180),
  ('NG.L', 'UK', '公益', 'Gas Utilities', 190),
  ('REL.L', 'UK', '資本財・産業', 'Business Services', 200),
  ('RIO.L', 'UK', '素材', 'Metals & Mining', 210),
  ('ULVR.L', 'UK', '生活必需品', 'Household Products', 220),
  ('VOD.L', 'UK', 'コミュニケーション', 'Telecom Services', 230),
  ('AIR.PA', 'EU', '資本財・産業', 'Aerospace & Defense', 240),
  ('ALV.DE', 'EU', '金融', 'Insurance', 250),
  ('ASML.AS', 'EU', 'テクノロジー', 'Semiconductor Equipment', 260),
  ('BAS.DE', 'EU', '素材', 'Chemicals', 270),
  ('BNP.PA', 'EU', '金融', 'Banks', 280),
  ('DTE.DE', 'EU', '公益', 'Integrated Utilities', 290),
  ('ENEL.MI', 'EU', '公益', 'Electric Utilities', 300),
  ('ISP.MI', 'EU', '金融', 'Banks', 310),
  ('MC.PA', 'EU', '一般消費財', 'Luxury Goods', 320),
  ('OR.PA', 'EU', '生活必需品', 'Personal Care', 330),
  ('SAN.PA', 'EU', 'ヘルスケア', 'Pharmaceuticals', 340),
  ('SAP.DE', 'EU', 'テクノロジー', 'Application Software', 350),
  ('SIE.DE', 'EU', '資本財・産業', 'Electrical Equipment', 360),
  ('SU.PA', 'EU', 'エネルギー', 'Integrated Oil & Gas', 370)
on conflict (symbol) do update
set region = excluded.region,
    sector = excluded.sector,
    industry = excluded.industry,
    priority = excluded.priority,
    updated_at = now();
